#!/usr/bin/env bash
# Regenerates APP_INVENTORY.md from the live RouterEmu/ source tree.
# Run manually, or let .github/workflows/update-app-docs.yml run it on every PR.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT=APP_INVENTORY.md
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# App Inventory"
  echo
  echo "> Auto-generated by \`scripts/update_app_docs.sh\` — do not edit by hand."
  echo "> Last updated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
  echo
  echo "Source tree: \`RouterEmu/\` (extracted from \`RouterEmu.zip\`)."
  echo
  echo "| File | Lines |"
  echo "|---|---:|"
} > "$TMP"

# Stable, sorted inventory of every source/config file in the app.
if [ -d RouterEmu ]; then
  find RouterEmu -type f \
    ! -path '*/.gradle/*' ! -path '*/build/*' ! -name '.DS_Store' \
    | LC_ALL=C sort \
    | while IFS= read -r f; do
        lines=$(wc -l < "$f" | tr -d ' ')
        printf '| `%s` | %s |\n' "$f" "$lines" >> "$TMP"
      done
fi

{
  echo
  echo "## Totals"
  echo
  echo "- Files: $(find RouterEmu -type f ! -path '*/.gradle/*' ! -path '*/build/*' ! -name '.DS_Store' | wc -l | tr -d ' ')"
  echo "- Lines: $(find RouterEmu -type f ! -path '*/.gradle/*' ! -path '*/build/*' ! -name '.DS_Store' -print0 | xargs -0 cat 2>/dev/null | wc -l | tr -d ' ')"
} >> "$TMP"

# Only rewrite if content (ignoring the timestamp line) changed, so CI can
# detect "no docs change" cheaply.
if [ -f "$OUT" ] && diff -q <(grep -v '^> Last updated:' "$OUT") <(grep -v '^> Last updated:' "$TMP") >/dev/null 2>&1; then
  echo "APP_INVENTORY.md already up to date."
else
  mv "$TMP" "$OUT"
  trap - EXIT
  echo "APP_INVENTORY.md updated."
fi
